name = "Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20f49a4a02ab7e809c507e6bcc1711b398b948ce984db754c661e22b12891aa0"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
